services:
  next:
    build: .
    ports:
      - 3000:3000
      - 54321:54321
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
